FROM tomcat:8.0.52-jre8


COPY ./files/local_policy.jar /docker-java-home/jre/lib/security
COPY ./files/US_export_policy.jar /docker-java-home/jre/lib/security
COPY ./files/input.properties /usr/local/tomcat/webapps/
COPY ./files/LiveSpread-SQL.war /usr/local/tomcat/webapps/

CMD ["catalina.sh", "run"]
