version: '3'
services: 
  mssql:
    image: "microsoft/mssql-server-linux:latest"
    ports:
      - "1433:1433"
    volumes:
      - mssql:/var/opt/mssql
    environment:
      ACCEPT_EULA: 'Y'
      SA_PASSWORD: "B@TMAN206"

volumes:
  mssql:  